# Ubuntu 14.04
sudo: required
dist: trusty

# Enable C++ support
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: 
        - COMPILER=g++-4.9
        - BASE=/home/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: 
        - COMPILER=g++-5
        - BASE=/home/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: 
        - COMPILER=g++-6
        - BASE=/home/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/
    - os: linux 
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: 
        - COMPILER=clang++-3.6
        - BASE=/home/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - BASE=/home/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: 
        - COMPILER=/usr/bin/clang
        - BASE=/Users/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/include
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: 
        - COMPILER=/usr/bin/clang
        - BASE=/Users/travis/build/juliangaal
        - INSTALL_PATH=/usr/local/include

# Install necessary dependencies
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libblas-dev liblapack-dev; else brew update && sudo rm /usr/local/include/c++ && brew install lapack liblas openblas; fi
  - mkdir QuantStack && cd QuantStack
  - git clone https://github.com/QuantStack/xtl.git
  - cd xtl && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -DCMAKE_CXX_COMPILER=$COMPILER ..
  - sudo make install 
  - cd $BASE/kalman/QuantStack
  - git clone https://github.com/QuantStack/xtensor.git
  - cd xtensor && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -DCMAKE_CXX_COMPILER=$COMPILER ..
  - sudo make install 
  - cd $BASE/kalman/QuantStack
  - git clone https://github.com/QuantStack/xtensor-blas.git
  - cd xtensor-blas && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PATH -DCMAKE_CXX_COMPILER=$COMPILER ..
  - sudo make install 
  - cd $BASE/kalman/
  - rm -rf QuantStack
  - cd $BASE/kalman/

# Build steps
script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make -j
